### ISSUE TITLE
module.openshift.aws_iam_instance_profile.openshift-instance-profile: "roles": [DEPRECATED] Use `role` instead. Only a single role can be passed to an IAM Instance Profile

### ISSUE THREAD

**Issue by jagannathsarma** [dwmkerr/terraform-aws-openshift#11]
Hi Dave,
Can you please check the below error.

Error : Error applying plan:

1 error(s) occurred:

* module.openshift.aws_iam_instance_profile.openshift-instance-profile: 1 error(s) occurred:

* aws_iam_instance_profile.openshift-instance-profile: Error creating IAM instance profile openshift-instance-profile: EntityAlreadyExists: Instance Profile openshift-instance-profile already exists.
	status code: 409, request id: 36715f10-5cf2-11e7-b146-e900a1ed359e

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.

**Comment by jagannathsarma** [comment]
Changed few lines in 03-roles.tf
`resource "aws_iam_policy_attachment" "openshift-attachment-forward-logs" {
    name       = "openshift-attachment-forward-logs"
 -  roles      = ["${aws_iam_role.openshift-instance-role.name}"]
 +  role      = "${aws_iam_role.openshift-instance-role.name}"
    policy_arn = "${aws_iam_policy.openshift-policy-forward-logs.arn}"
  }
  
  //  Create a instance profile for the role.
  resource "aws_iam_instance_profile" "openshift-instance-profile" {
    name  = "openshift-instance-profile"
 -  roles = ["${aws_iam_role.openshift-instance-role.name}"]
 +  role = "${aws_iam_role.openshift-instance-role.name}"`

but got error on openshift-attachment-forward-logs removed it then was able to get openshift running. But this is just a workaround that  I tried.

please try fixing these issues, as this repo is pretty much helpful for anyone who is trying to play with openshift.

**Comment by dwmkerr** [comment]
Hi @jagannathsarma I'll look into this this week.

One quick question - it looks like the setup failed because the role already existed. Have you tried removing all resources created by terraform and recreating?

**Comment by jagannathsarma** [comment]
@dwmkerr yes Dave I tried it then it worked with above mentioned edits, but cloud trail is giving issues so to make this setup work I have disabled cloud trail in my setup. and Even tried enabled hawkular-metrics from the link that you provided in docs, unfortunately that did not work.

**Comment by dwmkerr** [comment]
Hmm definitely something weird going on. I've had trouble with roles before, I might be wrong but from memory there are some thing terraform cannot easily do with roles because it can be difficult to tell when they are fully created. I'll take a look

**Comment by dwmkerr** [comment]
This issue has been solved, but for anyone who sees something similar, make sure to update your terraform client since these changes went in!
