### ISSUE TITLE
Support Persistent Volumes

### ISSUE THREAD

**Issue by dwmkerr** [dwmkerr/terraform-aws-openshift#3]
Two options:

a. AWS EFS. Easy, but only available in a few regions
b. AWS EBS. Harder, single AZ only, but global.

Probably go for the first one to start with

**Comment by jayunit100** [comment]
maybe get fancy and do container native gluster?

**Comment by jayunit100** [comment]
Another option I've heard of is just NFS on a AWS node.

**Comment by dwmkerr** [comment]
Gluster would be nice, I'm working with a team who are migrating to it at the moment, so far the easiest option I've seen is AWS EFS (which is basically NFS on a node but as a managed service), unfortunately not available in all regions yet! I'm actually working on an example of splunk integration, then will take a look at persistence. I'm thinking of adding 'recipes' to this repo, which are pull requests I leave open showing the changes you need to make to a 'vanilla' setup to add specific features (user management, persistent volumes etc, what do you think?)

**Comment by jayunit100** [comment]
Cool.  Yeah I did gluster on a kube cluster this week ; it wasn't too bad; actually there's a good terraform recipe I used for it ... the glue was to add endpoints to a service definition that pointed to your gluster nodes.

**Comment by dwmkerr** [comment]
That's cool :) I've managed to get an EBS backed docker file storage for the nodes now in the current master branch, which is correctly formatted for docker storage which is cool, the other very exciting change is the 'splunk' recipe I'm just finishing which shows how to integrate with splunk, this'll be ready to publish in a few datys
