### ISSUE TITLE
'make ssh-[master|node1|node2]' does no longer work

### ISSUE THREAD

**Issue by ribeaud** [dwmkerr/terraform-aws-openshift#32]
Hi,
For some reason I currently do not understand, I'm no longer able to directly SSH access the _master_ resp. the _nodes_. `make ssh-master` does no longer work (it used to). `ssh master.openshift.local` from the **bastion** does not work neither. However my **OpenShift** installation works perfectly.
I see that the **EC2** instances are using the _openshift_ key pair name. However I do not own this key (has this key been stored somewhere on the **bastion**?). How could I now access the _master_ resp. the _nodes_? Is there a documented or non-documented to do it?
Thanks and cheers,
christian

**Comment by dwmkerr** [comment]
Very strange, I did a fresh checkout and it worked fine for me with the latest code.

Can you try running:

```
ssh-add ~/.ssh/id_rsa
```

To make sure your local identity is added?  I wonder if your ssh agent is not running, so unable to forward your identity to the bastion...

**Comment by ribeaud** [comment]
Hi. Just tried out now. Worked like a charm. Thank you. christian.

**Comment by dwmkerr** [comment]
no worries!
