### ISSUE TITLE
deploy with openshift release-3.6 not found playbooks/deploy_cluster.yml

### ISSUE THREAD

**Issue by liuyuewen91** [dwmkerr/terraform-aws-openshift#60]
in openshift  git repo:
https://github.com/openshift/openshift-ansible

in branche 3.6 it hase no playbooks/deploy_cluster.yml

and install_from_bastion.sh 

```
# Run the playbook.
ANSIBLE_HOST_KEY_CHECKING=False /usr/local/bin/ansible-playbook -i ./inventory.cfg ./openshift-ansible/playbooks/prerequisites.yml
ANSIBLE_HOST_KEY_CHECKING=False /usr/local/bin/ansible-playbook -i ./inventory.cfg ./openshift-ansible/playbooks/deploy_cluster.yml
```
bring me the error.

i saw in readme  v3.6 is tested

**Comment by dwmkerr** [comment]
I've created a release branch which should work for you, the details are here:

https://github.com/dwmkerr/terraform-aws-openshift#choosing-the-openshift-version

If there are any issues just let me know!
