### ISSUE TITLE
Use Elastic IPs for the various instances 

### ISSUE THREAD

**Issue by hferentschik** [dwmkerr/terraform-aws-openshift#62]
If Elastic IPs are used for each instance, the whole cluster can be stopped and restarted without any issues. This allows to create the cluster once and only start it when needed. 

Atm, a restart of the cluster leads new IPs getting assigned to the instances, making it hard to ssh into the machine and even worse breaking the public route of the master.

Since aws_eip does not have a public DNS attribute (see https://github.com/terraform-providers/terraform-provider-aws/issues/1149) and since the DNS attribute of the instance does not get updated once the Elastic IP is assigned, one needs for now to remove the use of public DNS names of the nodes. This does not have any impact on the functionality of the cluster though.

**Comment by dwmkerr** [comment]
Just merged into `master` now!
