### ISSUE TITLE
Could not open to access the console in the browser

### ISSUE THREAD

**Issue by skatdutta** [dwmkerr/terraform-aws-openshift#71]
Hi Dave,
Able to install openshift and could verify that pods are running but could not access the
console as the installation did not promt the console URL at the end.

further trying this, following error comes -
[ec2-user@ipx.x.x.x terraform-aws-openshift]$ make browse-openshift
open $(terraform output master-url)
Couldn't get a file descriptor referring to the console
[ec2-user@ipx.x.x.x terraform-aws-openshift]$ 

Could you please let us know how to access the console in the browser?

**Comment by dwmkerr** [comment]
That's really odd. Can I infer from the output that you were running the `makefile` from another EC2 instance rather than a local machine?
