### ISSUE TITLE
openshift_hostname is replaced by Removed

### ISSUE THREAD

**Issue by ezeev** [dwmkerr/terraform-aws-openshift#75]
I'm doing a clean install on AWS following the steps in the README. `make infrastructure` succeeds. `make openshift` fails with the following error:

```
Failure summary:


  1. Hosts:    ip-REDACTED.us-west-2.compute.internal
     Play:     Verify Requirements
     Task:     Run variable sanity checks
     Message:  last_checked_host: ip-REDACTEDus-west-2.compute.internal, last_checked_var: openshift_master_manage_htpasswd;Found removed variables: openshift_hostname is replaced by Removed: See documentation; 
make: *** [openshift] Error 2
```

I just cloned the master branch of this repo today:

```
git describe
v3.10-6-g4f3dd43
```

Any idea what is causing this?

**Comment by mathus13** [comment]
@ezeev Have you had any luck? I know I removed no variables, how about you?

**Comment by ezeev** [comment]
@mathus13 - No luck. We decided to move on to the OpenShift 4.0 developer preview. The installer works awesome. https://try.openshift.com

**Comment by dwmkerr** [comment]
According to this issue:

https://github.com/openshift/openshift-ansible/issues/9665

`openshift_hostname` is no longer a valid configuration value - it seemed to be causing a number of issues (#40 as an example). I am removing the usage of `openshift_hostname` and re-testing. If it works, I'll release an update and close this issue.
